// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEducacao.GestaoAluno.Data;

#nullable disable

namespace PlataformaEducacao.GestaoAluno.Data.Migrations
{
    [DbContext(typeof(GestaoAlunoContext))]
    [Migration("20260702222349_SqlServerBaseline")]
    partial class SqlServerBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlataformaEducacao.GestaoAluno.Domain.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacao.GestaoAluno.Domain.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoVerificacao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoVerificacao")
                        .IsUnique();

                    b.HasIndex("MatriculaId")
                        .IsUnique();

                    b.ToTable("Certificados", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacao.GestaoAluno.Domain.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SituacaoMatricula")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Matriculas", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacao.GestaoAluno.Domain.ProgressoAula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId");

                    b.ToTable("ProgressoAulas", (string)null);
                });

            modelBuilder.Entity("PlataformaEducacao.GestaoAluno.Domain.Aluno", b =>
                {
                    b.OwnsOne("PlataformaEducacao.Core.DomainObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AlunoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("AlunoId");

                            b1.ToTable("Alunos");

                            b1.WithOwner()
                                .HasForeignKey("AlunoId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaEducacao.GestaoAluno.Domain.Certificado", b =>
                {
                    b.HasOne("PlataformaEducacao.GestaoAluno.Domain.Matricula", "Matricula")
                        .WithOne("Certificado")
                        .HasForeignKey("PlataformaEducacao.GestaoAluno.Domain.Certificado", "MatriculaId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("PlataformaEducacao.GestaoAluno.Domain.Matricula", b =>
                {
                    b.HasOne("PlataformaEducacao.GestaoAluno.Domain.Aluno", "Aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.OwnsOne("PlataformaEducacao.GestaoAluno.Domain.HistoricoAprendizado", "HistoricoAprendizado", b1 =>
                        {
                            b1.Property<Guid>("MatriculaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DataConclusao")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataConclusao");

                            b1.Property<double>("ProgressoGeralCurso")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("float")
                                .HasDefaultValue(0.0)
                                .HasColumnName("ProgressoGeralCurso");

                            b1.Property<int>("SituacaoCurso")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("SituacaoCurso");

                            b1.Property<int>("TotalAulasCurso")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("TotalAulasCurso");

                            b1.HasKey("MatriculaId");

                            b1.ToTable("Matriculas");

                            b1.WithOwner()
                                .HasForeignKey("MatriculaId");
                        });

                    b.Navigation("Aluno");

                    b.Navigation("HistoricoAprendizado")
                        .IsRequired();
                });

            modelBuilder.Entity("PlataformaEducacao.GestaoAluno.Domain.ProgressoAula", b =>
                {
                    b.HasOne("PlataformaEducacao.GestaoAluno.Domain.Matricula", "Matricula")
                        .WithMany("ProgressoAulas")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("PlataformaEducacao.GestaoAluno.Domain.Aluno", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("PlataformaEducacao.GestaoAluno.Domain.Matricula", b =>
                {
                    b.Navigation("Certificado");

                    b.Navigation("ProgressoAulas");
                });
#pragma warning restore 612, 618
        }
    }
}
