apiVersion: v1
kind: Service
metadata:
  name: bff-api
  namespace: plataforma-educacao
spec:
  type: ClusterIP
  selector:
    app: bff-api
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-api
  namespace: plataforma-educacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-api
  template:
    metadata:
      labels:
        app: bff-api
    spec:
      containers:
        - name: bff-api
          image: rinaldoserra/plataforma-educacao-bff-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: plataforma-config
            - secretRef:
                name: plataforma-secret
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/ready
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
