apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bff-api-hpa
  namespace: plataforma-educacao
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bff-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gestao-identidade-api-hpa
  namespace: plataforma-educacao
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gestao-identidade-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gestao-conteudo-api-hpa
  namespace: plataforma-educacao
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gestao-conteudo-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gestao-aluno-api-hpa
  namespace: plataforma-educacao
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gestao-aluno-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gestao-financeira-api-hpa
  namespace: plataforma-educacao
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gestao-financeira-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
