apiVersion: v1
kind: Secret
metadata:
  name: plataforma-secret
  namespace: plataforma-educacao
  labels:
    app: plataforma-educacao
  annotations:
    description: "Secrets de exemplo para ambiente de desenvolvimento. Em producao, utilizar sealed-secrets ou external-secrets."
type: Opaque
data:
  AppSettings__Secret: "YzFmNTFmNDItNTcyNy00ZDE1LWI3ODctYzZiYmJiNjQ1MDI0"
  SA_PASSWORD: "UGxhdGFmb3JtYUAyMDI2"
  ConnectionStrings__GestaoIdentidade: "U2VydmVyPXNxbHNlcnZlciwxNDMzO0RhdGFiYXNlPUdlc3Rhb0lkZW50aWRhZGU7VXNlciBJZD1zYTtQYXNzd29yZD1QbGF0YWZvcm1hQDIwMjY7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVl"
  ConnectionStrings__GestaoConteudo: "U2VydmVyPXNxbHNlcnZlciwxNDMzO0RhdGFiYXNlPUdlc3Rhb0NvbnRldWRvO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9UGxhdGFmb3JtYUAyMDI2O1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZQ=="
  ConnectionStrings__GestaoAluno: "U2VydmVyPXNxbHNlcnZlciwxNDMzO0RhdGFiYXNlPUdlc3Rhb0FsdW5vO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9UGxhdGFmb3JtYUAyMDI2O1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZQ=="
  ConnectionStrings__GestaoFinanceira: "U2VydmVyPXNxbHNlcnZlciwxNDMzO0RhdGFiYXNlPUdlc3Rhb0ZpbmFuY2VpcmE7VXNlciBJZD1zYTtQYXNzd29yZD1QbGF0YWZvcm1hQDIwMjY7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVl"
