apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: plataforma-educacao
data:
  datasource.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
  dashboards.yml: |
    apiVersion: 1

    providers:
      - name: Plataforma Educacao
        orgId: 1
        folder: Plataforma Educacao
        type: file
        disableDeletion: true
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
